### 调试数据的草稿

In [1]:
from  dataLoader import *
from shenzhenDataset import *
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
x = unimib_load_dataset()

x_train shape is (6055, 1, 1, 150), x_test shape is (1524, 1, 1, 150)
y_train shape is (6055, 9), y_test shape is (1524, 9)


In [3]:
x.x_test

array([[[[9.25274045, 8.60111606, 7.94187478, ..., 9.18787481,
          9.17632538, 9.12367525]]],


       [[[8.48176772, 8.37970617, 8.50029873, ..., 8.94645706,
          8.95710963, 8.94679036]]],


       [[[8.63925573, 8.70672724, 8.5753431 , ..., 9.53327861,
          9.53680204, 9.3398423 ]]],


       ...,


       [[[9.07265608, 9.05663397, 9.0944033 , ..., 9.1199903 ,
          9.0805523 , 9.09936177]]],


       [[[9.1343688 , 9.09288571, 9.11314443, ..., 9.13421959,
          9.13285095, 9.04936111]]],


       [[[9.1560194 , 9.11126954, 9.07506116, ..., 9.20394567,
          9.12918919, 9.14560825]]]])

In [4]:
from LoadRealRunningJumping import *
from torch.utils import data

In [5]:
train_set = Running_Or_Jumping(incl_xyz_accel = True, incl_rms_accel = False, is_normalize = True, data_mode = 'Train')

data shape is (1200, 3, 1, 150), label shape is (1200, 1)
Jumping label is 1, has 600 samples, Running label is 0, has 600 samples


In [6]:
from scipy import io

In [7]:
path_in = './UniMiB-SHAR/data'
adl_data = io.loadmat(path_in + '/adl_data.mat')['adl_data']
adl_names = io.loadmat(path_in + '/adl_names.mat', chars_as_strings=True)['adl_names']
adl_labels = io.loadmat(path_in + '/adl_labels.mat')['adl_labels']

In [8]:
adl_data.shape, adl_names.shape, adl_labels.shape

((7579, 453), (9, 1), (7579, 3))

In [9]:
#Reshape data and compute total (rms) acceleration
num_samples = 151
#UniMiB SHAR has fixed size of 453 which is 151 accelX, 151 accely, 151 accelz
adl_data = np.reshape(adl_data,(-1,num_samples,3), order='F')
#uses Fortran order
adl_data.shape

(7579, 151, 3)

In [10]:
adl_data[:600].shape

(600, 151, 3)

In [11]:
adl_names.shape

(9, 1)

In [12]:
adl_labels.shape

(7579, 3)

In [16]:
train_uni = unimib_load_dataset(incl_xyz_accel = True, incl_rms_accel = False, incl_val_group = False, is_normalize = True, one_hot_encode = False, data_mode = 'Train', single_class = True, class_name = 'Running', verbose=False)
print()
test_uni = unimib_load_dataset(incl_xyz_accel = True, incl_rms_accel = False, incl_val_group = False, is_normalize = True, one_hot_encode = False, data_mode = 'Test', single_class = True, class_name = 'Running')

x_train shape is (6055, 3, 1, 150), x_test shape is (1524, 3, 1, 150)
y_train shape is (6055,), y_test shape is (1524,)
return single class data and labels, class is Running
train_data shape is (1572, 3, 1, 150), test_data shape is (413, 3, 1, 150)
train label shape is (1572,), test data shape is (413,)

x_train shape is (6055, 3, 1, 150), x_test shape is (1524, 3, 1, 150)
y_train shape is (6055,), y_test shape is (1524,)
return single class data and labels, class is Running
train_data shape is (1572, 3, 1, 150), test_data shape is (413, 3, 1, 150)
train label shape is (1572,), test data shape is (413,)


In [3]:
sz_train = shenzhen_dataset(data_size=1000, data_mode='Train',verbose=False)
sz_test = shenzhen_dataset(data_size=1000, data_mode='Test',verbose=False)

In [13]:
one = train_uni[-1][0]
one[2]

array([[-0.28975987, -0.54573868, -0.79847812, -0.82051059, -0.672393  ,
        -0.50922418, -0.29416457, -1.4842214 , -0.93396129,  0.25792552,
         1.04358658,  1.84173235,  1.95846491,  1.46980001,  0.3790472 ,
         0.34038982,  1.28068165,  0.96147874,  0.47298199,  0.25501337,
         0.00365564, -0.23475654, -0.30739614, -0.56773489, -0.64031517,
        -0.30004019, -0.28095492, -0.36635316, -0.66279267, -0.81913482,
        -0.21278066,  0.08050285,  0.8019193 ,  3.24156087,  2.37575625,
         0.32624645, -0.27020435, -1.25249807, -0.88966756,  0.53767404,
         0.70964721, -0.01770899, -0.63696455, -0.31736541, -0.47714565,
        -0.98713441, -1.07392182, -1.12538865, -1.73164068, -0.91280479,
         2.48524688,  3.17644494,  1.70787859, -0.23132433, -1.53259042,
        -1.2313474 ,  0.05396385,  1.09870829,  0.90159483,  0.37934815,
         0.1434018 , -0.1791352 , -0.26980644, -0.21075421, -0.14748875,
        -0.46753141, -0.93301894, -0.93993183, -0.9

In [11]:
two = sz_train[-1][0]
two[10]

array([[-0.83411095,  2.58605569, -0.29970992, -0.19282971, -0.46003023,
        -0.0859495 , -0.32642997, -0.56691043,  2.90669631,  1.25005309,
        -0.40659012, -0.83411095, -0.67379064,  0.50189164,  0.18125102,
        -0.1393896 ,  0.23469112, -0.19282971, -0.67379064,  0.34157133,
        -0.83411095, -0.67379064, -0.83411095, -0.64707059, -0.46003023,
        -0.40659012, -0.0859495 , -0.78067085, -0.24626981, -0.51347033,
         0.55533175,  3.01357652, -0.62035054,  1.99821455,  1.91805439,
         1.83789424, -0.83411095,  0.34157133, -0.0325094 , -0.72723075,
        -0.72723075, -0.19282971, -0.40659012, -0.83411095,  1.3569333 ,
        -0.83411095, -0.83411095,  1.08973278,  1.83789424, -0.83411095,
        -0.46003023, -0.35315002, -0.19282971, -0.67379064,  0.02093071,
        -0.67379064,  0.82253226, -0.83411095, -0.83411095, -0.72723075]])

In [15]:
from LoadRealRunningJumping import Running_Or_Jumping
running = Running_Or_Jumping(incl_xyz_accel = True, incl_rms_accel = False, is_normalize = True, data_mode = 'Train')

data shape is (1200, 3, 1, 150), label shape is (1200, 1)
Jumping label is 1, has 600 samples, Running label is 0, has 600 samples


In [24]:
running[599][1]

array([1.])